apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins 
  namespace: ingress-nginx
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins-ci
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
