kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: ingress-nginx
  name: jenkins-ps
  labels:
    type: local
    app: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ingress-nginx
  name: jenkins-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
